### ISSUE TITLE
Validate when a line has only one targe.

### ISSUE THREAD

**Issue by sergioandresmeneses** [sergioandresmeneses/convert-Nginx-Redirect-Rules#1]
For example, when a  rule has only an origin or target.

**Comment by sergioandresmeneses** [comment]
It generates the following error and stops the execution:

```Formatting the TXT file...
Traceback (most recent call last):
  File "rules.py", line 83, in <module>
    convertTXT(str(fileToFormat))
  File "rules.py", line 58, in convertTXT
    urls[1] = urls[1].strip()
IndexError: list index out of range```

**Comment by sergioandresmeneses** [comment]
For troubleshooting, you can compare the output of lines in the final file so you can see where the process stopped:

``` cat rules-formatted.inc | wc -l && cat new-rules.txt | wc -l ```

**Comment by sergioandresmeneses** [comment]
As URLs don't include the "," character, we can validate its presence while reading the file line by line.
